### ISSUE TITLE
__tglib__ folder location change

### ISSUE THREAD

**Issue by julestechting** [nodegin/tglib#34]
Hi,
Is there a way to change the __tglib__ folder location? It seems to be hardcoded in the client constructor to the node workdir:
`this.appDir = path.resolve(process.cwd(), '__tglib__', crc32(`${type}${value}`).toString())`

As this folder is storing the auth key and the log, I would like to put it outside the node folder.

Thank you.

**Comment by nodegin** [comment]
Hi, this is current not possible since tglib will locate for `__tglib__` in current working directory, but in my personal favour I think the data directory is better to stick with the project directory.

The possible solution according to your issue is to create a empty folder outside project folder, then execute something like `ln -s ../mydata ./__tglib__` before running your script. However, if you think it is better to add an option to allow specifying `appDir`, feel free to open a PR.

**Comment by julestechting** [comment]
Thanks for the suggestion. The symbolic link would allow to store __tglib__ directory on another drive but not to put it out of the node process folder. I'm looking for a way to put the cached key away from unwanted access.
I'll think about it further. Maybe I'll open a PR. In any case, thanks a lot for the idea.

**Comment by nodegin** [comment]
This is now possible for v2.1, I have added an option `dataDir` for specifying data directory.

**Comment by julestechting** [comment]
Amazing! I'll test it today. Thank you, @nodegin!
